# The base hadoop image to use for all components.
# See this repo for image build details: https://github.com/Comcast/kube-yarn/tree/master/image
image:
  repository: danisla/hadoop
  tag: 2.9.0
  pullPolicy: IfNotPresent

# The version of the hadoop libraries being used in the image.
hadoopVersion: 2.9.0

# Select antiAffinity as either hard or soft, default is soft
antiAffinity: "soft"

hdfs:
  nameNode:
    pdbMinAvailable: 1

    resources:
      requests:
        memory: "4000Mi"
        cpu: "4000m"
      limits:
        memory: "4000Mi"
        cpu: "4000m"

  dataNode:
    replicas: 3

    pdbMinAvailable: 1

    resources:
      requests:
        memory: "8000Mi"
        cpu: "3000m"
      limits:
        memory: "8000Mi"
        cpu: "3000m"

  webhdfs:
    enabled: false

yarn:
  resourceManager:
    pdbMinAvailable: 0

    resources:
      requests:
        memory: "256Mi"
        cpu: "100m"
      limits:
        memory: "256Mi"
        cpu: "200m"

  nodeManager:
    pdbMinAvailable: 0

    # The number of YARN NodeManager instances.
    replicas: 0

    # Create statefulsets in parallel (K8S 1.7+)
    parallelCreate: false

    # CPU and memory resources allocated to each node manager pod.
    # This should be tuned to fit your workload.
    resources:
      requests:
        memory: "500Mi"
        cpu: "100m"
      limits:
        memory: "500Mi"
        cpu: "100m"

persistence:
  nameNode:
    enabled: true
    storageClass: "local-storage-small"
    accessMode: ReadWriteOnce
    size: 6Gi

  dataNode:
    enabled: true
    storageClass: "local-storage-large"
    accessMode: ReadWriteOnce
    size: 50Gi
