image: psylvan/flink
imageTag: latest
imagePullPolicy: IfNotPresent

resources:
  jobmanager:
    limits:
      cpu: 4000m
      memory: 4096Mi
    requests:
      cpu: 4000m
      memory: 4096Mi
  taskmanager:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 1000m
      memory: 1024Mi

flink:
  jobmanager_heap_mb: 4096
  taskmanager_heap_mb: 1024
  num_taskmanagers: 150
  num_slots_per_taskmanager: 1

  ## Other config options for flink-conf.yaml
  #config: |
  #  some.option: 3

hadoop:
  core-site.xml: |
    <?xml version="1.0"?>
    <?xml-stylesheet type="text/xsl" href="configuration.xsl"?>
    <configuration/>
