image: psylvan/clonos
imageTag: latest
imagePullPolicy: IfNotPresent

resources:
  jobmanager:
    limits:
      cpu: 8000m
      memory: 8192Mi
    requests:
      cpu: 4000m
      memory: 8192Mi
  taskmanager:
    limits:
      cpu: 2000m
      memory: 1524Mi
    requests:
      cpu: 1000m
      memory: 1524Mi

flink:
  jobmanager_heap_mb: 6192
  taskmanager_heap_mb: 1524
  num_taskmanagers: 150
  num_slots_per_taskmanager: 1

  ## Other config options for flink-conf.yaml
  #config: |
  #  some.option: 3

hadoop:
  core-site.xml: |
    <?xml version="1.0"?>
    <?xml-stylesheet type="text/xsl" href="configuration.xsl"?>
    <configuration/>
